### ISSUE TITLE
Nothing happens when moving selection to trash

### ISSUE THREAD

**Issue by pglira** [dylanaraps/fff#104]
After selecting files with ``d`` and pressing ``p`` to move them to the trash folder the question dialog appears. After confirming it with ``y`` nothing happens - the files are still there. What could be the problem?

**Comment by dylanaraps** [comment]
Which version of `fff` are you using (`fff -v`)?

**Comment by pglira** [comment]
fff 2.1

**Comment by Mashn** [comment]
I can reproduce this, the problem resolves after cleaning the trash.

**Comment by dylanaraps** [comment]
Is this related to files already existing in the trash?

**Comment by pglira** [comment]
The trash folder is empty. I tried it with the default one (``~/.local/share/fff/trash/``) and to set it to ``~\trash``.  In both cases nothing happens when I try to delete any file or folder.

**Comment by dylanaraps** [comment]
This is the command to trash files:

```sh
: "${FFF_TRASH:=${XDG_DATA_HOME:=${HOME}/.local/share}/fff/trash}"
cd "$FFF_TRASH" && mv -f "$@"
```

Does this work?:

```sh
cd "${FFF_TRASH:=${XDG_DATA_HOME:=${HOME}/.local/share}/fff/trash}"
```

**Comment by pglira** [comment]
Yes it works.

``cd "${FFF_TRASH:=${XDG_DATA_HOME:=${HOME}/.local/share}/fff/trash}"``

brings me to

``~/.local/share/fff/trash``

That folder exists and I have read and write permissions for it.

**Comment by teotwawki16** [comment]
I can reproduce this but with directories:
```
~ $ ls -la ~/.local/share/fff/trash/
total 12
drwxr-xr-x 3 apod users 4096 Apr  4 12:50 .
drwxr-xr-x 3 apod users 4096 Apr  4 00:28 ..
drwx------ 2 apod users 4096 Apr  4 01:51 mc
```
And then the default fff trash command:
```
~ $ mv -f mc/ ~/.local/share/fff/trash/
mv: cannot move 'mc/' to '/home/apod/.local/share/fff/trash/mc': Directory not empty
```

**Comment by Gigahawk** [comment]
Can confirm I have the same issue, deletes only seem to fail on folders sometimes.

It might be worth changing the trash directory to use the whole path of the incoming file to preserve information about where it comes from.

**Comment by dylanaraps** [comment]
The `mv` command currently works like this: 

```sh
# First change directory to trash directory.
cd "$FFF_TRASH"

# All arguments are full paths to selected files.
# Last argument is `.`, telling `mv` to move the list of files to the current directory.
mf -f /path/to/file1 /path/to/file2 /path/to/example_dir/ .
```

I'm looking into fixing this issue.

**Comment by dylanaraps** [comment]
Changing `mv` for a `cp` then an `rm` will solve the issue. The `mv` command can't "merge" directories which is causing the issue.

Example:

```sh
# Create hard links to the trashed files in the trash directory.
# Also preserve ownership and permissions.
cp -al /path/to/file1 /path/to/file2 /path/to/example_dir/ .

# Delete the linked files in their original locations,
# effectively "moving" the files to the trash.
rm -r /path/to/file1 /path/to/file2 /path/to/example_dir/
```

**Comment by dylanaraps** [comment]
Fixed.

New solution:

```sh
cd "$FFF_TRASH" || cmd_line "error: Can't cd to trash directory."
cp -alf "$@" && rm -r "${@:1:$#-1}"
```

This has the added benefit of being even faster than plain `mv`. As creating hard links is faster than actually moving the data!
