### ISSUE TITLE
Moving downwards while searching triggers bulk rename: Anyway to disable that?

### ISSUE THREAD

**Issue by qazip** [dylanaraps/fff#111]
Moving downwards while searching triggers bulk rename: Anyway to disable that? I don't like having to press "esc" or "enter" after searching.

How it is:
- Go to a folder;
- Search for mkv;
- Press the down arrow;
- fff changes to the rename function;

How I would like it to be:
- Go to a folder;
- Search for mkv;
- Press the down arrow;
- fff goes to the line below;

**Comment by dylanaraps** [comment]
You're meant to press enter before you can scroll through the search results.
