### ISSUE TITLE
Error deleting files

### ISSUE THREAD

**Issue by Mashn** [dylanaraps/fff#113]
I get sometimes this error when I try delete a file.

"cp: cannot create hard link './archieve.pdf' to '/home/mhf/test/archieve.pdf': Invalid cross-device link"

**Comment by dylanaraps** [comment]
Is this on the latest `git` master or is this the latest release?

**Comment by Mashn** [comment]
On latest git. This happen specifically on directory where I mount my other hard drive: /media/1Tb.

**Comment by dylanaraps** [comment]
Try the latest commit and let me know if it works.

**Comment by Mashn** [comment]
It's working now. Thanks very much!
