### ISSUE TITLE
Problem when export FFF_KEY_BULK_RENAME

### ISSUE THREAD

**Issue by Andrikin** [dylanaraps/fff#118]
I'm having a interesting problem when I try to modificate both FFF_KEY_BULK_RENAME and FFF_KEY_BULK_RENAME_ALL keybinding to any other letter. I follow the instructions in the section "Customizing the keybindings.",modifing those values in my .bashrc file, avoiding conflicts with others keybindings. So far, so good.
The problem appears after I try bulk rename a file, showing this terminal output message: /usr/bin/fff: linha 902: /home/yada yada/file.name: Permissão negada.
The line 902 in /usr/bin/fff is this: "${file_program[@]}" "${marked_files[@]}" . Seaching for the declaration of ${file_program}, I found this:  b|B) file_program=(bulk_rename) ;;
Then, I modified this line to: "${FFF_KEY_BULK_RENAME}"|"${FFF_KEY_BULK_RENAME_ALL}") file_program=(bulk_rename) ;; 
And work it!
Now I think this will alow me to modify any file operation the proper way. But, this is the right thing to do?
Sorry, English isn't my firt language, feel free to correct me! :D

**Comment by dylanaraps** [comment]
Fixed. Thanks for the detailed report. :)
