### ISSUE TITLE
Shall fff add multi-columns?

### ISSUE THREAD

**Issue by icyhat** [dylanaraps/fff#119]
We know that some times we wanna search all file in a directory by eyes,  due to 2 Dimension Screen, can we add multi-columns, no need to much,  3 columns are enough to satisfy to our eyes

**Comment by dylanaraps** [comment]
This isn't currently possible nor was it the intention when writing the code. Everything would need a rewrite to support this. `fff` also does the TUI entirely by hand and my headache level was high enough already!!
