### ISSUE TITLE
Is this compatible with sh?

### ISSUE THREAD

**Issue by tonijarjour** [dylanaraps/fff#121]
Would it be possible to use this script in Dash? It is much faster than Bash, with the caveat being it won't work with newer features like `[[`.

**Comment by dylanaraps** [comment]
You can use this regardless of which shell is currently in use. All you need is `bash` installed to run it. There is no way for this to be ported to POSIX `sh` as it makes heavy use of arrays and `read` features exclusive only to `bash` (*especially `-n1`*).
