### ISSUE TITLE
Extracting archives, no manual refresh option?

### ISSUE THREAD

**Issue by lwilletts** [dylanaraps/fff#125]
At the moment I have a simple opener script to use with fff, which contains the following line:

```
application/zip*) unzip "$1" ;;
```

This unzips the given file, but fff doesn't auto update to show the new directory/files within it. Auto updating is a separate issue, preferably there would be someway for the user to send a signal in a script to fff to refresh the screen, but more so the bigger issue is there's no keybinding for the user to refresh the screen manually using a hotkey. At the moment I have to leave the directory then reenter it to see the updated list. Perhaps a good default free hotkey for this could be 'R'.

**Comment by dylanaraps** [comment]
This is currently mapped to `e` and you can remap it by changing the `FFF_KEY_REFRESH` environment variable.:

```
        # Refresh current dir.
        ${FFF_KEY_REFRESH:=e})
            open "$PWD"
        ;;
```

**Comment by lwilletts** [comment]
It's not listed in the man page, although it is in the readme.
