### ISSUE TITLE
Visual bugs and slowdown while navigating list

### ISSUE THREAD

**Issue by mohd-akram** [dylanaraps/fff#14]
See https://asciinema.org/a/e9GjTGzoP7MwNS4HOqFgA23bA

**Comment by danishprakash** [comment]
@dylanaraps would you mind explaining the problem here, please? I would love to put in a fix for this if possible.

**Comment by parrotgeek1** [comment]
It's echoing the arrow keys control characters as they are pressed. Seems like an stty issue

**Comment by dylanaraps** [comment]
The characters echo when “read” can’t keep up with user input or when f_print takes too long. 

The fix is simple for both. I’m going overseas tomorrow so it will take me some time.

**Comment by dylanaraps** [comment]
Does this issue still occur?

**Comment by mohd-akram** [comment]
Still happens.

**Comment by dylanaraps** [comment]
Latest master should be a lot more responsive. I've figured out what's causing the visual bugs as well. Just need to work on a fix. The issue stems from the draw function taking too long when too many list items are visible at once.

**Comment by dylanaraps** [comment]
I've started rewriting the entire program to scroll properly. It also won't be the minified comment-less mess it is now. Try out https://github.com/dylanaraps/fff/pull/45 and let me know if the performance is better now.

It's currently a separate file called `fuck` and it has no features minus scroll right now. I uploaded it early so performance can be tested. :+1:

**Comment by mohd-akram** [comment]
The new version doesn't scroll down properly for me, it just stays on the second line while iterating through the list. When going back up, it colors the background red of each item and the previous highlighting doesn't get removed. I'm on macOS 10.14.2 using the default bash.

**Comment by dylanaraps** [comment]
What terminal emulator are you using?

**Comment by mohd-akram** [comment]
Terminal.

**Comment by dylanaraps** [comment]
Does iTerm2 or another terminal emulator work? The rewrite works in every terminal emulator I can test on Linux.

**Comment by mohd-akram** [comment]
It works beautifully in iTerm2. Odd.

**Comment by dylanaraps** [comment]
I'll try and find an old version of a terminal emulator and see if I can reproduce this.

**Comment by dylanaraps** [comment]
Terminal.app probably doesn't support the escape sequences for scroll (despite them being VT100).

**Comment by dylanaraps** [comment]
Found a terminal with the same behavior. Working on a fix.

**Comment by dylanaraps** [comment]
Try out the PR again.

**Comment by dylanaraps** [comment]
The issue should be fixed now. 

(Note: there may be a hang when the window is resized. it's a bug.)

**Comment by mohd-akram** [comment]
Yup, works!

**Comment by dylanaraps** [comment]
Awesome :)

I'll close this when I release the new version.

**Comment by dylanaraps** [comment]
New version is out :)

**Comment by mohd-akram** [comment]
Nice, just tried it out. Quick thing I noticed - I can't seem to scroll with up/down arrow, only with k/j (tested on both iTerm and Terminal).

**Comment by dylanaraps** [comment]
I can reproduce this. Working on a fix.

**Comment by dylanaraps** [comment]
Fixed. :)
