### ISSUE TITLE
Quick install suggestion

### ISSUE THREAD

**Issue by Roy-Orbison** [dylanaraps/fff#165]
```sh
wget -q https://github.com/dylanaraps/fff/raw/master/fff && sudo install fff /usr/local/sbin/ && rm fff
```

**Comment by Roy-Orbison** [comment]
@dylanaraps Good point.

**Comment by Roy-Orbison** [comment]
So did you think this was Hacktoberfest or something? It's not, and it's not even a PR.

**Comment by dylanaraps** [comment]
No. There's just no point to this issue at all.

**Comment by Roy-Orbison** [comment]
The extra steps in your manual install process are antithetical. Unzip? Make? It's a single file.

Github already serves it with gzip compression. If `master` isn't always the stable version, have a `stable` branch that always points to the latest tagged release.

**Comment by dylanaraps** [comment]
Installation instructions aren't gospel. Stop wasting my time.
