### ISSUE TITLE
How to know that i'am in a shell opened by fff 

### ISSUE THREAD

**Issue by plavenu** [dylanaraps/fff#169]
Hello all,

it possible to know that we are in fff after opening shells in it ?

To be more clearful : 

> open fff then open a shell !
> reopen a fff in this shell ! 
> and so on ...

How to know that i'am in a shell opened by fff ?

Thanks for you tool.

**Comment by dimo414** [comment]
[`pstree -sa $$`](https://manpages.debian.org/pstree) will show you the parents of the current process; which will include a `bash /path/to/fff` line if you're within a `fff`-created shell. There are other similar commands if `pstree` isn't quite what you want.

`fff` also exports a [`FFF_LEVEL`](https://github.com/dylanaraps/fff/blob/5045c4a/fff#L871) variable to the subshell's environment, but unless that's documented to always be set (in future versions of `fff`, I mean) it may be safer to treat that as an implementation detail and instead inspect the process tree.

**Comment by plavenu** [comment]
So great @dimo414 this exactly what  i want 
Great thanks.
