### ISSUE TITLE
[enhancement] ueberzug instead of w3m-img for image previews

### ISSUE THREAD

**Issue by pfr-dev** [dylanaraps/fff#175]
I don't suppose this is something that you might consider?

ueberzug is superior to w3m-img

Also, just FYI, you can update your "Distros" to include NetBSD. Install with `pkgin install fff`

**Comment by Lunatic1985** [comment]
> I don't suppose this is something that you might consider?
> 
> ueberzug is superior to w3m-img
> 
> Also, just FYI, you can update your "Distros" to include NetBSD. Install with `pkgin install fff`

Hi, Does seeing image previews work for you? i installed the dependencies (gentoo) in sowm and i can't see anything, i get an error "your window manager says it doesn't support net_active_ window blah blah

**Comment by Ramiferous** [comment]
> Hi, Does seeing image previews work for you? i installed the dependencies (gentoo) in sowm and i can't see anything, i get an error "your window manager says it doesn't support net_active_ window blah blah

Hey, yeah it works using `w3m-img` and I've even forked another fork of `fff` which uses `ueberzug` so you can always try that. 

I dont know about that error though, it should work with `sowm` as that is dylans creation too. Perhaps if the window is too small for te image? try in a fullscreen terminal? 
Perhaps try another window manager to see whether it's an `fff` problem or an `sowm` problem.

**Comment by Lunatic1985** [comment]
yes, it's strange that it doesn't work, can you share your fork to test?
:)

**Comment by Lunatic1985** [comment]
yeah same error with fullscreen (st and xterm)

**Comment by Lunatic1985** [comment]
Same exact error with your fork  ;/, normal-full screen with st

**Comment by pfr-dev** [comment]
> 
> 
> Same exact error with your fork ;/, normal-full screen with st

Hmm it must be a `sowm` issue then. Have you tried with another wm? I dont use `sowm` so I cant really help sorry.

**Comment by Lunatic1985** [comment]
yeah, the problem* is sowm, dwm work just fine.

**Comment by dylanaraps** [comment]
It's not a sowm issue. w3m-img and ueberzug work via hacks to begin with. See https://github.com/dylanaraps/neofetch/issues/1392
