### ISSUE TITLE
cd to directory on quit?

### ISSUE THREAD

**Issue by jessemillar** [dylanaraps/fff#18]
I'd love to use this to navigate quickly to other directories and have my terminal actually end up in those directories after exiting via `q`. Does this functionality exist currently and I just missed it?

**Comment by Fortyseven** [comment]
I was looking for this, as well. Maybe a key to do that, if not by default. ("c" [change dir], "o" [open directory]...? I dunno. :P)

**Comment by Anachron** [comment]
In order to be able to do it you need to `source <script>` (in bash) or `. <script>` (posix) in order to keep the directory where you were switching to.  Else the directory will be preserved when the command `fff` exists.

So it will make `fff` a bit more complicated.

**Comment by dylanaraps** [comment]
I discovered a way of doing this without needing further configuration. Will implement it today.

**Comment by skywind3000** [comment]
any progress ?? I really need this feature .

**Comment by skywind3000** [comment]
ranger have a `ranger_cd` command to do similar thing.

**Comment by skywind3000** [comment]
https://github.com/jarun/nnn/issues/183
nnn can do so

**Comment by dylanaraps** [comment]
fwiw, this is how the feature has been implemented in previous `fff` versions.

```sh
    # Modification to one of the last lines in script.
    trap "refresh; printf '\\e[m\\e[?25h\\e[?7h'; cd \$PWD; exec \$SHELL" EXIT
```

The above is a hack and causes issues in some systems. Which is why it was removed. 

Now the reason every file manager has some kind of hack; either an `alias` or a helper script etc is because of the way shells work. When you launch a program the shell spawns it in a subshell and any changes that happen to the environment are discarded when the program exits.

**Comment by Anachron** [comment]
@dylanaraps which is exactly what I was talking about 2 months earlier in https://github.com/dylanaraps/fff/issues/18#issuecomment-432802687 *sigh*.

**Comment by dylanaraps** [comment]
CD on exit is done. This is the least intrusive way I've found.

```sh
# Example setup (bash)
alias f="fff; cd \$(< ~/.fff_d)"

# Example setup (posix) (non-bash)
alias f="fff; cd \$(cat ~/.fff_d)"

# Customization (temporary file to use) (optional)
export FFF_CD_FILE=~/.fff_d
```
