### ISSUE TITLE
Remove (potential) pirated contents from screencast

### ISSUE THREAD

**Issue by shirishp** [dylanaraps/fff#21]
<img width="374" alt="screenshot 2018-10-24 at 9 14 52 pm" src="https://user-images.githubusercontent.com/328026/47443415-dff03c00-d7d1-11e8-96b4-96ab5363a030.png">

The screencast at 00:04 location contains files which looks like pirated contents.
Can we please remove it and replace with some other content?

**Comment by parrotgeek1** [comment]
Why do you care?
