### ISSUE TITLE
Customizable keybindings and/or Emacs-inspired alternative keybindings?

### ISSUE THREAD

**Issue by jimeh** [dylanaraps/fff#22]
Any chance keybindings might be made customizable?

Or at least I'd love a Emacs-inspired alternative mode instead of the VIM-inspired defaults.

**Comment by dylanaraps** [comment]
I’ll look into this. Shouldn’t be too difficult to add.

**Comment by dylanaraps** [comment]
Done.

**Comment by jimeh** [comment]
Awesome, thanks :D
