### ISSUE TITLE
[feature] "Drop into shell" command

### ISSUE THREAD

**Issue by norcalli** [dylanaraps/fff#23]
With `ranger`, I tend to use the `s` key to drop into a the default login shell in the current directory often. This might be related to generally adding keybindings or shortcuts, but I think it would be useful.

**Comment by dylanaraps** [comment]
This will be easy to add. I’m picturing a mapping to “!” that spawns a shell (or even just a little prompt). 

- can use $SHELL to spawn the correct shell (or bash if empty since we know it’s installed)
- can add new keybindings to the current shell (maybe escape to go back to fff)

**Comment by norcalli** [comment]
Current shell can return upon exiting, so no keybindings are required. A key to launch a login shell by itself in the current directory would be good, and would take care of most use cases.

The `!` key could be useful for operating on marked files, but I'm also wondering if there's a way to make those marked files available to the shell, perhaps as an environment variable. That could allow us to mark files and the operate on them. And by marked files, I mean the ones marked for copy or move.

**Comment by mikhailnov** [comment]
+1
