### ISSUE TITLE
[bug] Cancel search filter

### ISSUE THREAD

**Issue by norcalli** [dylanaraps/fff#24]
There seems to be no way to cancel text input or search filters right now. As a workaround, I press `.` twice, toggling hidden files and then untoggling, therefore reloading the directory listing.

**Comment by dylanaraps** [comment]
The current way is to click enter (or backspace) when input (or backspace) is empty to cancel. I should also add a mapping for escape to this same action. 

What did you have in mind?

**Comment by norcalli** [comment]
I don't believe escape is mapped to anything as it stands, so my potential candidates are `Esc` and `Ctrl-G` from emacs world.

**Comment by dylanaraps** [comment]
Done (escape now works).
