### ISSUE TITLE
open file using macOS default

### ISSUE THREAD

**Issue by zachvalenta** [dylanaraps/fff#30]
this seems to work for `.pdf` and `.png` but not so for `.md` or code files (everything opens in Vim)

be nice if `fff` followed the macOS default for a file type

![screen shot 2018-10-26 at 3 15 43 pm](https://user-images.githubusercontent.com/11388735/47587789-0c22ce80-d932-11e8-9e6e-953338936d23.png)

**Comment by dylanaraps** [comment]
You need to set `$EDITOR` to sublime text. `open`/`xdg-open` are used for binary files and `$EDITOR` is used for text files.

**Comment by zachvalenta** [comment]
gotcha, cheers!
