### ISSUE TITLE
[Feature Request] Customize colors for different file types

### ISSUE THREAD

**Issue by KevCui** [dylanaraps/fff#32]
It would be cool if fff can support customized colors for different file types, or apply dir_colors color configuration.

**Comment by dylanaraps** [comment]
This would have to be done on the file extension (instead of the mime-type). It's not cheap to check mime-type in bash which is why we only use it to open files.

We can use `LS_COLORS`/`dircolors` though.

**Comment by KevCui** [comment]
Nice! Works great! :clap: 

One small thing, there are some errors in terminal regarding "*" in `dir_colors`

```
/dev/stdin: line 1: *TODO=07;38;5;250: command not found
/dev/stdin: line 1: *todo=07;38;5;250: command not found
```

It doesn't support `*extension` in `dir_colors`:

```
*extension color-sequence
    Specifies the color used for any file that ends in extension. 
```

Details: https://linux.die.net/man/5/dir_colors

**Comment by dylanaraps** [comment]
Thanks.

Will fix this now. :+1:

**Comment by dylanaraps** [comment]
Quick question: Does `*TODO=07;38;5;250` match files with an extension named `TODO` (`.TODO`) or files that include the string `TODO`?

**Comment by dylanaraps** [comment]
Try out #49 again. Code needs some cleaning but it works great on my end. :)

**Comment by KevCui** [comment]
Great! It works on my machine :wink:
