### ISSUE TITLE
[Feature request] homebrew package

### ISSUE THREAD

**Issue by antoniodini** [dylanaraps/fff#34]
Easier to install and mantain under macos
thanks

**Comment by mgiugliano** [comment]
Don't forget the man page:
ln -s ~/fff/fff.1 /usr/local/share/man/man1


P.S. I am also in favour of porting it to the home brew package managers under macOs

**Comment by lougehrig10** [comment]
[Made a pull request to homebrew-core](https://github.com/Homebrew/homebrew-core/pull/35994)

**Comment by dylanaraps** [comment]
Any update on this?

**Comment by LoganDark** [comment]
@dylanaraps see https://github.com/Homebrew/homebrew-core/pull/35994 for updates

**Comment by dylanaraps** [comment]
I'm aware. I've posted twice in the homebrew repo asking for an update to the PR. I'm asking back in this repo to not clutter theirs. The PR has been inactive for over 14 days now. I'd open a new PR myself but homebrew's guidelines disallow this if there's already an open PR.

**Comment by LoganDark** [comment]
@dylanaraps don't clutter this one too then, maybe you should wait for their response

**Comment by lougehrig10** [comment]
fff 2.1 has been merged into homebrew-core
