### ISSUE TITLE
[Feature request] search in real time

### ISSUE THREAD

**Issue by maxlevesque** [dylanaraps/fff#35]
Hi, first of all thanks :) that's a nice and funny soft here.

Right now, the search is only applied when we press enter after /toto[ENTER].
What would be great is to be able to search "in real time", that is, only the files/folders compatible with ongoing search would be shown. For instance, If i'm willing to search for /toto, then when typing the first /tot, I would have only folders toti and toto shown.

Anyway thanks, :) and have fun

**Comment by dylanaraps** [comment]
Done.

**Comment by maxlevesque** [comment]
Cool :))) thanks :))

Le sam. 5 janv. 2019 à 12:49, Dylan Araps <notifications@github.com> a
écrit :
