### ISSUE TITLE
file path incorrect when going through root directory

### ISSUE THREAD

**Issue by nkg447** [dylanaraps/fff#37]
I added the following code at the starting of open() function 
`echo $1 >> out`

here is the 'out' file while using the fff
```
/home/nikunj
/home


//media
//media/nikunj
//media/nikunj/MJRO1714
//media/nikunj/MJRO1714/abc.avi
```

an extra '/' at the starting of the file path will prevent xdg-open to work correctly<br>
the following command did not work
`xdg-open '//media/nikunj/MJRO1714/abc.avi'`
the result to the above command was
```
main.go:63: openFile: "/nikunj/MJRO1714/abc.avi"
main.go:70: stat /nikunj/MJRO1714/abc.avi: no such file or directory

```

**Comment by dylanaraps** [comment]
This should be fixed now.
