### ISSUE TITLE
Weird behavior on long key presses

### ISSUE THREAD

**Issue by teotwawki16** [dylanaraps/fff#46]
Pressing the arrow keys (scrolling up or down/going back and forth directories) for long periods make fff behave weird (hanging of some sort and weird characters flashing around the terminal). Like its queuing all the long key presses until it stops. And I can't do anything unless the 'key-press queuing' ends. And after it, fff behaves fine again.

**Comment by dylanaraps** [comment]
Fixed in  #45. 

It's a full rewrite of the script. There are a few bugs I'm aware of but nothing major. Try it out. :)

**Comment by dylanaraps** [comment]
Fixed in master now.
