### ISSUE TITLE
Use XDG_ variables for directories

### ISSUE THREAD

**Issue by Crestwave** [dylanaraps/fff#50]
It would make sense to honor this since `fff` uses `xdg-utils` by default. This would also make it more portable, eliminating the need to add a special fallback for directories on operating systems like Haiku.

The variables could either be swapped out for it (e.g. `$FFF_TRASH` could be replaced with `$XDG_CACHE_HOME/fff/trash`), or it could be used as a fallback if it exists instead of a hardcoded path (e.g. the line `: "${FFF_TRASH:=$XDG_CACHE_HOME/fff/trash}"` could be added).

**Comment by dylanaraps** [comment]
See #51
