### ISSUE TITLE
Allow search to go more than 1 level deep

### ISSUE THREAD

**Issue by unbrand** [dylanaraps/fff#54]
When I search for a file, I'd like fff to find results that are more than 1 level deep. Or maybe this currently works as designed? If so, a quick mention of this behavior in the Readme would be good.

**Comment by dylanaraps** [comment]
I can add this as an alternative hotkey for a multi level search. It's just a matter of changing a few lines.

**Comment by dylanaraps** [comment]
We should be able to do 2 level search rather quickly on second thought.

**Comment by dylanaraps** [comment]
Try out #55. The hotkey is `?`. This searches a second level deep. It's noticeably slower than regular search.

**Comment by dylanaraps** [comment]
Search will stay single level as there's no performant way of making this multi-level. I am working on a feature to allow you to call custom scripts (*you can bind a key to open `fzf` for example*).

**Comment by Crestwave** [comment]
> Search will stay single level as there's no performant way of making this multi-level. I am working on a feature to allow you to call custom scripts (_you can bind a key to open `fzf` for example_).

Shouldn't #55 be closed, then?
