### ISSUE TITLE
go to dir does not expand home nor tab complete

### ISSUE THREAD

**Issue by reavessm** [dylanaraps/fff#64]
typing  `:~/src` does not find `/home/reavessm/src` but typing the full name does.  Also, it would be nice to have tab complete on names.

**Comment by dylanaraps** [comment]
Fixed `~` not working.

https://github.com/dylanaraps/fff/commit/76c74b5dd2a1b127c64e1fadd96d30a820b12275

**Comment by dylanaraps** [comment]
Tab complete will take a little more time.

**Comment by dylanaraps** [comment]
Tab completion is done. https://github.com/dylanaraps/fff/commit/0a78e661c3b5e229a03f9cec928997298dd675b4

Let me know if there are any issues. :)
