### ISSUE TITLE
Please allow for a customized TRASH action

### ISSUE THREAD

**Issue by Anachron** [dylanaraps/fff#66]
So far you always move the trash to the `$FFF_TRASH` directory:

https://github.com/dylanaraps/fff/blob/master/fff#L337-L348

But some people (like me) wrote their own trash command (which actually prevents some files to be trashed and stores meta-information like modification time, owner, original path etc along with a meta-file).

I would love to have a `$FFF_TRASH_CMD` that gets checked and run and only if not set, `fff` should execute an `mv` command.

**Comment by dylanaraps** [comment]
Would something like this work?:

```sh
        cd "$FFF_TRASH" && "${FFF_TRASH_CMD:-mv}" "$@"
```

**Comment by Anachron** [comment]
Yep it would.

**Comment by dylanaraps** [comment]
`fff` passes arguments like this to `mv`: `mv /path/to/file1 /path/to/file2 /path/to/file3 .` with `.` being the current directory (`FFF_TRASH`). How would this work?

**Comment by Anachron** [comment]
Ah okay! I will just ignore the extra `cd` then that is not needed. Thank you!

**Comment by dylanaraps** [comment]
This means that your script will also be passed the `.` for current directory. I think its safer to push a change to make sure `FFF_TRASH_CMD` is only passed a file list.

**Comment by Anachron** [comment]
Yep, that's fine, I can change my script accordingly to check the last param and if it's `.` then it will just ignore it. No big issue. Thank you for the quick resolve!

**Comment by dylanaraps** [comment]
I made the change anyway. I don't want any confusing behavior for users nor should they have to modify their scripts. This also removed the `cd` to the `fff` default trash directory. :)

https://github.com/dylanaraps/fff/commit/9295fd7109147381b61401bf564ab9b9d8ebaeae
