### ISSUE TITLE
To be able to edit configurations from own customization file on home folder.

### ISSUE THREAD

**Issue by thepenguinthatwants** [dylanaraps/fff#84]
Right now using archlinux so it installs in /usr/bin/fff

If its possible to edit configurations from  $HOME/.config/fff/fff.conf it gives easier way to handle dotfiles. 

Tho not sure if its the philosophy of this program. But it would make it more fun to customize it.

**Comment by dylanaraps** [comment]
I have no plans to add a config file for `fff`. This may change in the future. :+1:
