### ISSUE TITLE
Add a tab or a few spaces before every entry.

### ISSUE THREAD

**Issue by qazip** [dylanaraps/fff#85]
So, I don't like having the folders/files so close to the limit. I suggest adding a tab to each entry and a ">" to the selected entry. If you don't know what I mean, check out how "nnn" does it.

What do you think?

**Comment by dylanaraps** [comment]
Have a look at https://github.com/dylanaraps/fff/pull/87. It allows you to customize the format string of both normal and marked files. Let me know if this allows you to customize `fff` to your needs. :)

**Comment by qazip** [comment]
Nice! Thank you. When you make a release with this fix I'll make sure to test it. Thank you man, you're awesome!

**Comment by qazip** [comment]
Hey @dylanaraps, the FILE_FORMAT option seems to work but the MARK_FORMAT does not. Can you please test it on your side again and let me know if it works? I have:

`export FFF_MARK_FORMAT="> %f"`

and it doesn't work.

**Comment by dylanaraps** [comment]
```sh
FFF_MARK_FORMAT="> %f" fff
```

This works for me.

![fff](https://user-images.githubusercontent.com/6799467/52422645-25294700-2aff-11e9-908f-a33f39a4b596.jpg)

**Comment by Anachron** [comment]
It works here as well.
