### ISSUE TITLE
cpu 100% usage

### ISSUE THREAD

**Issue by necronoise** [dylanaraps/fff#88]
I have no idea why but in voidlinux if you use fff from the repo or even here (github), randomly the process just open using 100% of my cpu, I have no idea how to reproduce this, I just installed it and happens whenever I use it or not.

![image](https://user-images.githubusercontent.com/28832216/52122236-6b673d80-2609-11e9-9c91-f0adb160b314.png)
![image](https://user-images.githubusercontent.com/28832216/52122238-6f935b00-2609-11e9-9653-4b5c3f4f14a1.png)

Im using VoidLinux, kernel linux 4.19.19_1, bspwm, xst.
Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz.
HP family graphic cards 3000.

**Comment by dylanaraps** [comment]
Does it happen in other terminal emulators? Also, does this happen after using a specific feature or is it through regular directory navigation?

**Comment by NicholasAzar** [comment]
noticed this happening to me too on osx with iterm2 and zsh.. Every once in a while I find one background fff process not attached to any TTY taking 100% cpu and needing to be killed manually. I'm not yet sure in what case that process gets spawned..

**Comment by dylanaraps** [comment]
Weird. `fff` calls `exit` on quit and the only time it backgrounds something is when it uses `xdg-open` (*or `open`*) to open a file in an external program. It also certainly doesn't execute itself.

Is this perhaps related to using `!` to spawn a subshell and then nesting multiple instances of `fff`? Or doe this happen after exiting `fff` using `Ctrl+C`, `q` or by closing the terminal window?

**Comment by dylanaraps** [comment]
Does the issue occur in the latest master? It's worth a try as well.

**Comment by dylanaraps** [comment]
I can reproduce the issue if I spawn a nested `fff` in a subshell using `!` and kill the parent terminal.

**Comment by NicholasAzar** [comment]
> I can reproduce the issue if I spawn a nested `fff` in a subshell using `!` and kill the parent terminal.

@dylanaraps yep! that did it for me too. Good catch

**Comment by dylanaraps** [comment]
Fixed. :)
