### ISSUE TITLE
Display issues in vim wrt long lines / tabs

### ISSUE THREAD

**Issue by mare-imbrium** [dylanaraps/fff#90]
When I open a text file using `fff` in Vim, the display is often jumbled. This does not happen if I open the same file in Vim through another command line program. 

The files usually have long lines and are tab delimited. This also happened when opening an HTML file.

**Comment by dylanaraps** [comment]
Does https://github.com/dylanaraps/fff/pull/91 fix the issue?

**Comment by rkumar** [comment]
[sample.zip](https://github.com/dylanaraps/fff/files/2829269/sample.zip)
Sorry for delay. Attached is tab delimited file that has display issues.

Will check out #91. Thanks a lot for the excellent utility.

**Comment by mare-imbrium** [comment]
> Does #91 fix the issue?

Yes. the issue is fixed by adding the two lines you gave.

Sorry, just realized it it `nvim` (neovim).

> NVIM v0.3.4
> Build type: Release
> LuaJIT 2.0.5

Thanks a lot.
