### ISSUE TITLE
fff not opening text files no matter what I set the variables as

### ISSUE THREAD

**Issue by anonaii** [dylanaraps/fff#94]
I've tried changed every variable I can think of (`EDITOR`,`VISUAL`,`FFF_OPENER`) to multiple different editors, but no matter what fff refuses to open files, it just blinks for a second and then goes back to normal.

**Comment by dylanaraps** [comment]
Output of this command?:

```sh
# Linux and Other
file -biL /path/to/file.txt

# macOS
file -bIL /path/to/file.txt
```

Also, what OS, terminal emulator, shell and editor are you using?

**Comment by anonaii** [comment]
```
[~]::file -biL test
text/plain; charset=us-ascii
```
I'm using Ubuntu, urxvt, fish (Tried with bash as well), and I tried nvim, vim, vi, and gedit.

**Comment by dylanaraps** [comment]
Is the issue fixed in master? I made some changes to the code a few days ago that could've fixed the issue.

```sh
git clone https://github.com/dylanaraps/fff
cd fff
./fff
```

**Comment by anonaii** [comment]
Ah, this version outputs the errors to stdout, apparently my VISUAL command (`urxvtc -e nvim`) wasn't running correctly.
